<?php
/**
 * IMI_Blog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       IMI
 * @package        IMI_Blog
 * @copyright      Copyright (c) 2018
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category list template
 *
 * @category    IMI
 * @package     IMI_Blog
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_categories = $this->getCategories(); ?>
<div class="page-title category-title">
    <h1><?php echo Mage::helper('imi_blog')->__('Categories') ?></h1>
</div>
<?php if ($_categories->getSize() > 0) :?>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <?php echo $this->getPagerHtml(); ?>
        <div class="category-list-container">
            <?php foreach ($_categories as $_category) : ?>
                <div class="category-list-item">
            <?php echo $_category->getName();?>
                </div>
            <?php endforeach;?>
        </div>
        <?php echo $this->getPagerHtml(); ?>
    <?php else : ?>
        <ul id="categories-list">
          <li>
              <a href=<?php echo Mage::getUrl('imi_blog/posts/index') ?>>
                <?php echo $this->__('All') ?>
              </a>
          </li>
            <?php foreach ($_categories as $_category) : ?>
                <?php echo $this->drawCategory($_category);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            blogTree('categories-list');
        </script>
    <?php endif;?>
<?php else : ?>
    <?php echo Mage::helper('imi_blog')->__('There are no categories at this moment');?>
<?php endif;?>
