<form action="<?php echo Mage::getUrl('imi_blog/inqueries/save'); ?>" method="post" id="add-new-inquiry" class="scaffold-form" enctype="multipart/form-data">
    <div class="fieldset">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <h2 class="legend"><?php echo $this->__('New Inquiry'); ?></h2>
        <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
        <?php echo $this->getChildHtml('global_messages'); ?>
         <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
        <ul class="form-list">
            <li class="fields">
                <div class="name-title">
                    <div class="field name-title">
                        <label for="title" class="required"><em>*</em> <?php echo $this->__('Title'); ?></label>
                        <div class="input-box">
                            <input type="text" id="title" name="title"
                                   title="<?php echo $this->__('Title'); ?>"
                                   maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                    <div class="field name-Content">

                        <label for="Content"  class="required"><em>*</em><?php echo $this->__('Content'); ?></label>

                        <div class="input-box">
                            <textarea name="content" id="content" title="content"
                                      class="required-entry input-text" cols="5" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="field name-pic">
                        <div class="input-box">
                            <input type="file" name="image" accept="image/*">
                        </div>
                    </div>
                </div>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link">
            <a href="
            <?php echo Mage::getUrl('imi_blog/inqueries/index'); ?>
            "><small>« </small><?php echo $this->__('Back'); ?></a></p>
        <button type="submit" title="Save Address" class="button">
            <span><span><?php echo $this->__('Save Inquiry'); ?></span></span>
        </button>
    </div>
</form>
<script type="text/javascript">
    //< ![CDATA[
    var inquiry = new VarienForm('add-new-inquiry');
    //]]>
</script>
