<?php
/**
 * IMI_Blog extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       IMI
 * @package        IMI_Blog
 * @copyright      Copyright (c) 2018
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Posts link widget template
 *
 * @category    IMI
 * @package     IMI_Blog
 * @author      Ultimate Module Creator
 */
?>
<?php $_posts = $this->getCurrentPosts();?>
<?php if ($_posts) :?>
    <div class="posts-widget-link">
        <a href="<?php echo $_posts->getPostsUrl()?>"><?php echo $_posts->getTitle()?></a>
    </div>
<?php endif;?>
